In [1]:
from sklearn.datasets import fetch_openml
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt

# Przygotowanie danych

In [2]:
mnist = fetch_openml('mnist_784', version=1, as_frame=False, parser='auto')
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]

# Zadanie 1

In [3]:
from sklearn.cluster import KMeans

In [4]:
k_list = [8, 9, 10, 11, 12]

In [5]:
k_means_models = []
for k in k_list:
    kmeans = KMeans(n_clusters=k, n_init=10)
    kmeans.fit_predict(X)
    k_means_models.append(kmeans)

In [6]:
k_means_models

[KMeans(n_init=10),
 KMeans(n_clusters=9, n_init=10),
 KMeans(n_clusters=10, n_init=10),
 KMeans(n_clusters=11, n_init=10),
 KMeans(n_clusters=12, n_init=10)]

# Zadanie 2

In [7]:
from sklearn.metrics import silhouette_score

In [8]:
kmeans_sil = [silhouette_score(X, model.labels_) for model in k_means_models]

In [9]:
with open('kmeans_sil.pkl', 'wb') as f:
    pickle.dump(kmeans_sil, f)

# Zadanie 3

In [10]:
kmeans_sil

[np.float64(0.07338974541854182),
 np.float64(0.056768504361405625),
 np.float64(0.058779462477890426),
 np.float64(0.05835878745275728),
 np.float64(0.05815240776276951)]

In [11]:
# Nie

# Zadanie 4

In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
conf_matrix = confusion_matrix(y, k_means_models[2].labels_)

In [14]:
print(conf_matrix)

[[ 290   43    7    4 5040  173 1260   74    3    9]
 [   8    6   10 3527    0    7    7    9 4293   10]
 [ 316  215   78  434   56  151  239  206  431 4864]
 [4604  185   46   53   21   33  508 1026  459  206]
 [   0 3733 2191  235    9  170  255   19  182   30]
 [2127  427  215  267   59   70 1845 1129  167    7]
 [  39   66    4   45   74 4443 1925   17  207   56]
 [   5 2085 4403  313   21    4   12   20  377   53]
 [1177  208  185  319   37   54  339 4120  334   52]
 [  86 3457 2852   93   50   16   31   87  267   19]]


# Zadanie 5

In [15]:
indeksy = set()
max_indexes = np.argmax(conf_matrix, axis=1)

for index in max_indexes:
    indeksy.add(index)

max_indexes = list(indeksy)
max_indexes.sort()

In [16]:
with open('kmeans_argmax.pkl', 'wb') as f:
    pickle.dump(max_indexes, f)

# Zadanie 6

In [17]:
dsts = []

for i in range(300):
    for j in range(X.shape[0]):
        distance = np.linalg.norm(X[i] - X[j])
        if distance != 0:
            dsts.append(distance)
    

In [18]:
dsts.sort()

In [19]:
dsts[:10]

[np.float64(279.26152617215286),
 np.float64(304.37641170103836),
 np.float64(317.5893575043093),
 np.float64(328.7658741414626),
 np.float64(333.4546445920344),
 np.float64(352.89800226127664),
 np.float64(355.1774204534967),
 np.float64(358.07401469528617),
 np.float64(359.64287842247063),
 np.float64(360.42474942767177)]

In [20]:
with open('dist.pkl', 'wb') as f:
    pickle.dump(dsts[:10], f)

# Zadanie 7

In [21]:
from sklearn.cluster import DBSCAN

In [22]:
ls = np.array(dsts[:3])

In [23]:
s = ls.mean()

In [24]:
epsilon = s
models = []

while(epsilon <= 1.1*s):
    model = DBSCAN(eps=epsilon)
    model.fit(X)
    models.append(model)
    epsilon += 0.04*s

In [25]:
lengths = []
for i in range(len(models)):
    lengths.append(len(np.unique(models[i].labels_)))

In [26]:
with open('dbscan_len.pkl', 'wb') as f:
    pickle.dump(lengths, f)